/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:04 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACM2SVTrustedDevicesViewControllerDelegate <NSObject>
@required
-(void)trustedDevicesViewControllerNeedsRefresh:(id)arg1;
-(void)trustedDevicesViewControllerDidSelectUnableReceiveMessages:(id)arg1;
-(void)downloadImageWithURL:(id)arg1 completionBlock:(/*^block*/id)arg2;
-(void)cancelInProgressImageDownloads;

@end

