/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:04 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMEUIController.h>

@interface ACMEUIController_Modern : ACMEUIController
-(Class)standardSignInClass;
-(Class)customSignInClass;
-(Class)iTunesSignInClass;
-(Class)signInWidgetClass;
@end

