/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:03 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACMExternalAppleConnectPrivate <ACMExternalAppleConnect>
@property (assign) id masterObject; 
@required
-(id)masterObject;
-(void)setMasterObject:(id)arg1;
-(BOOL)shouldReleaseOnMemoryWarning;

@end

