/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:04 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMAppleConnectImplComponents.h>

@interface ACMExternalAppleConnectImplComponents : ACMAppleConnectImplComponents
+(id)components;
-(id)createHandlerWithClass:(Class)arg1 context:(id)arg2 ;
-(id)twoSVController;
-(id)uiController;
-(id)createAppleConnectImpl;
-(id)createAppleConnectImplWithMasterObject:(id)arg1 ;
-(BOOL)uiControllerLoaded;
-(void)unloadUIController;
-(id)createAuthenticationRequest;
-(id)preferences;
@end

