/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:04 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMSignInDialogSimple_Modern.h>

@interface ACMSignInDialogSimple_iPad_Modern : ACMSignInDialogSimple_Modern
-(id)widget;
-(id)createCancelItem;
-(id)createIForgotItem;
-(void)buildWidgetContentGroupHorizontalConstraints;
-(double)widgetConstraintMultiplier;
-(double)widgetConstraintConstant;
-(unsigned long long)supportedInterfaceOrientations;
@end

