/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:04 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMSignInDialogCustom.h>
#import <libobjc.A.dylib/ACMSignInDialogSimpleProtocol.h>

@class UIImage, UIImageView, NSString, UIView, UIToolbar, NSArray, UIColor;

@interface ACMSignInDialogSimple_Modern : ACMSignInDialogCustom <ACMSignInDialogSimpleProtocol> {

	UIImage* _logo;
	UIImageView* _logoView;
	NSString* _accountNameFieldPlaceholder;
	UIView* _container;
	UIToolbar* _toolbar;
	NSArray* _burButtonItems;

}

@property (nonatomic,readonly) UIImage * iForgotImage; 
@property (nonatomic,retain) UIToolbar * toolbar;                                 //@synthesize toolbar=_toolbar - In the implementation block
@property (nonatomic,retain) UIImageView * logoView;                              //@synthesize logoView=_logoView - In the implementation block
@property (nonatomic,retain) NSArray * burButtonItems;                            //@synthesize burButtonItems=_burButtonItems - In the implementation block
@property (nonatomic,retain) UIView * container;                                  //@synthesize container=_container - In the implementation block
@property (nonatomic,readonly) double widgetConstraintMultiplier; 
@property (nonatomic,readonly) double widgetConstraintConstant; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign) id<ACMSignInDialogDelegate> delegate; 
@property (nonatomic,retain) NSString * requestedUserName; 
@property (readonly) NSString * userNameString; 
@property (assign) NSString * passwordString; 
@property (nonatomic,retain) UIImage * logo;                                      //@synthesize logo=_logo - In the implementation block
@property (nonatomic,retain) UIColor * backgroundColor; 
@property (nonatomic,retain) NSString * accountNameFieldPlaceholder;              //@synthesize accountNameFieldPlaceholder=_accountNameFieldPlaceholder - In the implementation block
-(void)setLogo:(UIImage *)arg1 ;
-(UIImage *)logo;
-(id)widget;
-(id)accountNameField;
-(void)checkFields;
-(BOOL)standardViewController;
-(void)setAccountNameFieldPlaceholder:(NSString *)arg1 ;
-(BOOL)userNameFieldEditable;
-(void)disableControls:(BOOL)arg1 ;
-(NSString *)accountNameFieldPlaceholder;
-(Class)widgetClass;
-(BOOL)shouldAuthenticateOnUserInput;
-(void)setBurButtonItems:(NSArray *)arg1 ;
-(UIImage *)iForgotImage;
-(id)createCancelItem;
-(id)createIForgotItem;
-(NSArray *)burButtonItems;
-(void)buildConstraints;
-(void)buildWidgetContentGroupHorizontalConstraints;
-(void)buildWidgetContentGroupVerticalConstraints;
-(double)widgetConstraintMultiplier;
-(double)widgetConstraintConstant;
-(void)buildHorizontalConstraints;
-(void)buildVerticalConstraints;
-(BOOL)shouldManuallyChangeStatusBarStyle;
-(id)darkDisabledTextColor;
-(BOOL)canSignIn;
-(void)dealloc;
-(id)tintColor;
-(void)loadView;
-(UIView *)container;
-(void)setContainer:(UIView *)arg1 ;
-(unsigned long long)supportedInterfaceOrientations;
-(void)viewDidAppear:(BOOL)arg1 ;
-(UIToolbar *)toolbar;
-(BOOL)shouldAutorotateToInterfaceOrientation:(long long)arg1 ;
-(void)setToolbar:(UIToolbar *)arg1 ;
-(long long)preferredStatusBarStyle;
-(BOOL)prefersStatusBarHidden;
-(id)darkTextColor;
-(id)passwordField;
-(UIImageView *)logoView;
-(void)setLogoView:(UIImageView *)arg1 ;
@end

