/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:03 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACMSignInDialogDelegate <NSObject>
@required
-(void)onIForgot:(id)arg1;
-(void)onSignIn:(id)arg1;
-(void)onSignInCancel:(id)arg1;
-(void)signInDialogWillBecomeEnabled;
-(void)signInDialogDidBecomeEnabled;
-(void)signInDialogWillBecomeDisabled;
-(void)signInDialogDidBecomeDisabled;

@end

