/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:22:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftCoreNFC.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NFCTagReaderSessionDelegate.h>

@interface CoreNFC.NFCTagReaderSessionDelegateSwiftWrapper : NSObject <NFCTagReaderSessionDelegate> {

	 swiftDelegate;

}
-(id)init;
-(void)tagReaderSession:(id)arg1 didInvalidateWithError:(id)arg2 ;
-(void)tagReaderSessionDidBecomeActive:(id)arg1 ;
-(void)tagReaderSession:(id)arg1 didDetectTags:(id)arg2 ;
@end

