/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:56 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftNetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Network._NWProtocol : _UKNOWN_SUPERCLASS_
@end

