/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTCameraManager.h>

@class RTDarwinNotificationHelper;

@interface RTCameraManager_Embedded : RTCameraManager {

	RTDarwinNotificationHelper* _notificationHelper;

}

@property (nonatomic,readonly) RTDarwinNotificationHelper * notificationHelper;              //@synthesize notificationHelper=_notificationHelper - In the implementation block
-(id)init;
-(void)dealloc;
-(void)_shutdown;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(RTDarwinNotificationHelper *)notificationHelper;
-(void)handleCameraPowerNotification:(id)arg1 ;
-(void)_handleCameraPowerNotification:(id)arg1 ;
@end

