/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:44 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTDataProtectionManagerNotificationUnlockedSinceBoot : RTNotification {

	BOOL _unlockedSinceBoot;

}

@property (nonatomic,readonly) BOOL unlockedSinceBoot;              //@synthesize unlockedSinceBoot=_unlockedSinceBoot - In the implementation block
-(BOOL)unlockedSinceBoot;
-(id)initWithUnlockedSinceBoot:(BOOL)arg1 ;
@end

