/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:41 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTService.h>

@protocol RTUserDefaults;
@interface RTDefaultsManager : RTService {

	id<RTUserDefaults> _userDefaults;

}
-(id)init;
-(id)objectForKey:(id)arg1 ;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(void)registerDefaults:(id)arg1 ;
-(void)shutdown;
-(void)addDomain:(id)arg1 ;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(id)initWithUserDefaults:(id)arg1 customDomain:(id)arg2 ;
-(void)notifyUpdatedKeys:(id)arg1 ;
-(void)registerDefault:(id)arg1 forKey:(id)arg2 ;
-(id)objectForKey:(id)arg1 domain:(id)arg2 ;
-(void)setObject:(id)arg1 forKey:(id)arg2 domain:(id)arg3 ;
@end

