/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSString, NSNumber, NSSet;

@interface RTEventLocationIdentifierMO : NSManagedObject

@property (nonatomic,retain) NSString * name; 
@property (nonatomic,retain) NSNumber * source; 
@property (nonatomic,retain) NSString * calendarIdentifier; 
@property (nonatomic,retain) NSSet * loiHistogramItems; 
+(id)managedObjectWithEventLocationIdentifier:(id)arg1 inManagedObjectContext:(id)arg2 ;
@end

