/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
#import <libcoreroutine.dylib/RTMetric.h>
#import <libobjc.A.dylib/RTMetricProtocol.h>

@class NSArray, NSString;

@interface RTFusionMetrics : RTMetric <RTMetricProtocol> {

	NSArray* _bluePOICandidates;
	NSArray* _localHintCandidates;
	NSArray* _learnedPlaceCandidatesExcludingHomeWork;
	NSArray* _learnedPlaceHomeWorkCandidates;

}

@property (nonatomic,retain) NSArray * bluePOICandidates;                                    //@synthesize bluePOICandidates=_bluePOICandidates - In the implementation block
@property (nonatomic,retain) NSArray * localHintCandidates;                                  //@synthesize localHintCandidates=_localHintCandidates - In the implementation block
@property (nonatomic,retain) NSArray * learnedPlaceCandidatesExcludingHomeWork;              //@synthesize learnedPlaceCandidatesExcludingHomeWork=_learnedPlaceCandidatesExcludingHomeWork - In the implementation block
@property (nonatomic,retain) NSArray * learnedPlaceHomeWorkCandidates;                       //@synthesize learnedPlaceHomeWorkCandidates=_learnedPlaceHomeWorkCandidates - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(SCD_Struct_RT8)event;
+(id)supportedMetricKeys;
+(id)booleanKeys;
+(id)unsignedIntegerKeys;
+(id)integerKeys;
+(id)doubleKeys;
+(id)bucketedKeys;
-(void)setMetricsUsingInputCandidates:(id)arg1 outputFusedInferredMapItems:(id)arg2 bestFusedInferredMapItem:(id)arg3 outputError:(id)arg4 ;
-(BOOL)submitMetricsWithError:(id*)arg1 ;
-(id)initWithLoggingEnabled:(BOOL)arg1 ;
-(void)setDerivedMetrics;
-(void)setInputMetrics:(id)arg1 ;
-(void)setOutputMetrics:(id)arg1 bestFusedInferredMapItem:(id)arg2 outputError:(id)arg3 ;
-(NSArray *)bluePOICandidates;
-(void)setBluePOICandidates:(NSArray *)arg1 ;
-(NSArray *)localHintCandidates;
-(void)setLocalHintCandidates:(NSArray *)arg1 ;
-(NSArray *)learnedPlaceCandidatesExcludingHomeWork;
-(void)setLearnedPlaceCandidatesExcludingHomeWork:(NSArray *)arg1 ;
-(NSArray *)learnedPlaceHomeWorkCandidates;
-(void)setLearnedPlaceHomeWorkCandidates:(NSArray *)arg1 ;
@end

