/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTInferredMapItemFuserParameters : NSObject {

	double _aoiConsiderThreshold;
	double _aoiUseThreshold;
	double _confidenceEqualityEpsilon;
	double _distanceThreshold;
	double _placeholderMultiplier;

}

@property (nonatomic,readonly) double aoiConsiderThreshold;                   //@synthesize aoiConsiderThreshold=_aoiConsiderThreshold - In the implementation block
@property (nonatomic,readonly) double aoiUseThreshold;                        //@synthesize aoiUseThreshold=_aoiUseThreshold - In the implementation block
@property (nonatomic,readonly) double confidenceEqualityEpsilon;              //@synthesize confidenceEqualityEpsilon=_confidenceEqualityEpsilon - In the implementation block
@property (nonatomic,readonly) double distanceThreshold;                      //@synthesize distanceThreshold=_distanceThreshold - In the implementation block
@property (nonatomic,readonly) double placeholderMultiplier;                  //@synthesize placeholderMultiplier=_placeholderMultiplier - In the implementation block
-(id)init;
-(id)description;
-(id)initWithDefaultsManager:(id)arg1 ;
-(double)confidenceEqualityEpsilon;
-(id)initWithAoiConsiderThreshold:(double)arg1 aoiUseThreshold:(double)arg2 confidenceEqualityEpsilon:(double)arg3 distanceThreshold:(double)arg4 placeholderMultiplier:(double)arg5 ;
-(double)aoiConsiderThreshold;
-(double)aoiUseThreshold;
-(double)distanceThreshold;
-(double)placeholderMultiplier;
@end

