/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface RTLearnedLocationReconcilerModelContext : NSObject {

	NSArray* _devices;
	NSArray* _overlappingVisits;

}

@property (nonatomic,retain) NSArray * devices;                        //@synthesize devices=_devices - In the implementation block
@property (nonatomic,retain) NSArray * overlappingVisits;              //@synthesize overlappingVisits=_overlappingVisits - In the implementation block
-(NSArray *)devices;
-(void)setDevices:(NSArray *)arg1 ;
-(void)setOverlappingVisits:(NSArray *)arg1 ;
-(NSArray *)overlappingVisits;
@end

