/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDateInterval;

@interface RTLocationStoreMetricOptions : NSObject {

	NSDateInterval* _dateInterval;
	double _uncertaintyThreshold;

}

@property (nonatomic,readonly) NSDateInterval * dateInterval;              //@synthesize dateInterval=_dateInterval - In the implementation block
@property (nonatomic,readonly) double uncertaintyThreshold;                //@synthesize uncertaintyThreshold=_uncertaintyThreshold - In the implementation block
-(id)init;
-(id)description;
-(NSDateInterval *)dateInterval;
-(id)initWithDateInterval:(id)arg1 uncertaintyThreshold:(double)arg2 ;
-(double)uncertaintyThreshold;
@end

