/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTInvocationDispatcher, NewMSPQuery;

@interface RTMapsSupportQueryState : NSObject {

	BOOL _loaded;
	unsigned long long _type;
	RTInvocationDispatcher* _dispatcher;
	NewMSPQuery* _query;

}

@property (nonatomic,readonly) unsigned long long type;                          //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) RTInvocationDispatcher * dispatcher;              //@synthesize dispatcher=_dispatcher - In the implementation block
@property (assign,nonatomic) BOOL loaded;                                        //@synthesize loaded=_loaded - In the implementation block
@property (nonatomic,retain) NewMSPQuery * query;                                //@synthesize query=_query - In the implementation block
+(id)queryTypeToString:(unsigned long long)arg1 ;
-(id)init;
-(id)description;
-(unsigned long long)type;
-(NewMSPQuery *)query;
-(void)setQuery:(NewMSPQuery *)arg1 ;
-(BOOL)loaded;
-(RTInvocationDispatcher *)dispatcher;
-(void)setLoaded:(BOOL)arg1 ;
-(id)initWithType:(unsigned long long)arg1 dispatcher:(id)arg2 ;
@end

