/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTMapItem;

@interface RTPinnedPlace : NSObject {

	unsigned long long _type;
	RTMapItem* _mapItem;

}

@property (nonatomic,readonly) unsigned long long type;              //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) RTMapItem * mapItem;                  //@synthesize mapItem=_mapItem - In the implementation block
-(id)init;
-(id)description;
-(unsigned long long)type;
-(RTMapItem *)mapItem;
-(id)initWithType:(unsigned long long)arg1 mapItem:(id)arg2 ;
@end

