/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSMutableDictionary;

@interface RTPlaceInferenceMetrics : NSObject {

	NSDate* _startDate;
	NSMutableDictionary* _metrics;

}

@property (nonatomic,readonly) NSDate * startDate;                         //@synthesize startDate=_startDate - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * metrics;              //@synthesize metrics=_metrics - In the implementation block
-(id)init;
-(id)description;
-(id)objectForKey:(id)arg1 ;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(NSDate *)startDate;
-(NSMutableDictionary *)metrics;
-(id)initWithClientIdentifier:(id)arg1 placeInferenceOptions:(id)arg2 ;
-(void)setPlaceInferences:(id)arg1 ;
-(void)setTopPersonalizedLabelsInferredMapItems:(id)arg1 topBluePOIInferredMapItem:(id)arg2 ;
-(void)submitMetrics;
-(void)setPlaceInferenceOptions:(id)arg1 ;
-(void)setTopPlaceInference:(id)arg1 ;
-(double)entropyOfConflictFromTopResults:(id)arg1 ;
@end

