/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTLocation;

@interface RTPotentialNoiseLocation : NSObject {

	BOOL _isNoise;
	RTLocation* _location;

}

@property (nonatomic,readonly) RTLocation * location;                    //@synthesize location=_location - In the implementation block
@property (assign,setter=setNoise:,nonatomic) BOOL isNoise;              //@synthesize isNoise=_isNoise - In the implementation block
-(RTLocation *)location;
-(id)initWithLocation:(id)arg1 ;
-(BOOL)isNoise;
-(void)setNoise:(BOOL)arg1 ;
@end

