/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTService.h>

@class NWPathEvaluator;

@interface RTReachabilityManager : RTService {

	BOOL _observingReachabilityChanges;
	NWPathEvaluator* _pathEvaluator;
	long long _currentReachability;

}

@property (nonatomic,retain) NWPathEvaluator * pathEvaluator;              //@synthesize pathEvaluator=_pathEvaluator - In the implementation block
@property (assign,nonatomic) long long currentReachability;                //@synthesize currentReachability=_currentReachability - In the implementation block
+(id)reachabilityToString:(long long)arg1 ;
-(id)init;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(NWPathEvaluator *)pathEvaluator;
-(long long)reachability;
-(void)setPathEvaluator:(NWPathEvaluator *)arg1 ;
-(void)_shutdown;
-(void)setCurrentReachability:(long long)arg1 ;
-(long long)currentReachability;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)fetchCurrentReachability:(/*^block*/id)arg1 ;
-(id)initWithPathEvaluator:(id)arg1 ;
-(void)_fetchCurrentReachability:(/*^block*/id)arg1 ;
-(void)_observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)_processReachabilityChange:(id)arg1 ;
-(id)currentReachabilityString;
@end

