/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@class RTMotionActivityManager, RTPlatform, RTWiFiFootprintMonitor;

@interface RTScenarioTriggerManager : RTNotifier {

	unsigned long long _interestedInConstantFootprint;
	unsigned long long _interestedInSettledState;
	RTMotionActivityManager* _motionActivityManager;
	unsigned long long _motionSettledState;
	RTPlatform* _platform;
	unsigned long long _settledState;
	unsigned long long _monitoredScenarioTriggerTypes;
	RTWiFiFootprintMonitor* _wifiFootprintMonitor;
	long long _wiFiFootprintState;

}

@property (assign,nonatomic) unsigned long long interestedInConstantFootprint;              //@synthesize interestedInConstantFootprint=_interestedInConstantFootprint - In the implementation block
@property (assign,nonatomic) unsigned long long interestedInSettledState;                   //@synthesize interestedInSettledState=_interestedInSettledState - In the implementation block
@property (nonatomic,retain) RTMotionActivityManager * motionActivityManager;               //@synthesize motionActivityManager=_motionActivityManager - In the implementation block
@property (assign,nonatomic) unsigned long long motionSettledState;                         //@synthesize motionSettledState=_motionSettledState - In the implementation block
@property (nonatomic,retain) RTPlatform * platform;                                         //@synthesize platform=_platform - In the implementation block
@property (assign,nonatomic) unsigned long long settledState;                               //@synthesize settledState=_settledState - In the implementation block
@property (assign,nonatomic) unsigned long long monitoredScenarioTriggerTypes;              //@synthesize monitoredScenarioTriggerTypes=_monitoredScenarioTriggerTypes - In the implementation block
@property (nonatomic,retain) RTWiFiFootprintMonitor * wifiFootprintMonitor;                 //@synthesize wifiFootprintMonitor=_wifiFootprintMonitor - In the implementation block
@property (assign,nonatomic) long long wiFiFootprintState;                                  //@synthesize wiFiFootprintState=_wiFiFootprintState - In the implementation block
+(id)settledStateName:(unsigned long long)arg1 ;
+(id)scenarioTriggerTypeToNotificationName:(unsigned long long)arg1 ;
-(id)init;
-(void)dealloc;
-(RTPlatform *)platform;
-(void)setPlatform:(RTPlatform *)arg1 ;
-(unsigned long long)monitoredScenarioTriggerTypes;
-(unsigned long long)settledState;
-(void)setSettledState:(unsigned long long)arg1 ;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(id)initWithMotionActivityManager:(id)arg1 wifiFootprintMonitor:(id)arg2 platform:(id)arg3 ;
-(RTMotionActivityManager *)motionActivityManager;
-(void)setMotionActivityManager:(RTMotionActivityManager *)arg1 ;
-(void)simulateScenarioTrigger:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)onMotionActivityManagerNotification:(id)arg1 ;
-(void)_evaluateSettledState;
-(void)onWiFiFootprintStateNotification:(id)arg1 ;
-(void)setWiFiFootprintState:(long long)arg1 ;
-(unsigned long long)interestedInSettledState;
-(void)setInterestedInSettledState:(unsigned long long)arg1 ;
-(void)_startMonitoringScenarioTriggerOfType:(unsigned long long)arg1 ;
-(void)_stopMonitoringScenarioTriggerOfType:(unsigned long long)arg1 ;
-(unsigned long long)_notificationNameToScenarioTriggerType:(id)arg1 ;
-(void)setMonitoredScenarioTriggerTypes:(unsigned long long)arg1 ;
-(void)setMotionSettledState:(unsigned long long)arg1 ;
-(void)_onMotionActivityManagerNotification:(id)arg1 ;
-(void)_onWiFiFootprintStateNotification:(id)arg1 ;
-(void)_postScenarioTriggerNotification:(id)arg1 ;
-(void)setInterestedInConstantFootprint:(unsigned long long)arg1 ;
-(void)postScenarioTriggerNotification:(id)arg1 ;
-(void)onPostScenarioTriggerNotificationFromDefaults;
-(unsigned long long)interestedInConstantFootprint;
-(unsigned long long)motionSettledState;
-(RTWiFiFootprintMonitor *)wifiFootprintMonitor;
-(void)setWifiFootprintMonitor:(RTWiFiFootprintMonitor *)arg1 ;
-(long long)wiFiFootprintState;
@end

