/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTSystemControl : NSObject
+(id)valueForKey:(id)arg1 ;
+(id)valueForMib:(int*)arg1 miblen:(int)arg2 ;
+(unsigned long long)sysctlByName:(id)arg1 ;
@end

