/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UNUserNotificationCenter;

@interface RTUserNotifications : NSObject {

	UNUserNotificationCenter* _notificationCenter;

}

@property (nonatomic,retain) UNUserNotificationCenter * notificationCenter;              //@synthesize notificationCenter=_notificationCenter - In the implementation block
-(id)init;
-(id)initWithBundleIdentifier:(id)arg1 ;
-(UNUserNotificationCenter *)notificationCenter;
-(void)setNotificationCenter:(UNUserNotificationCenter *)arg1 ;
-(void)postNotificationWithTitle:(id)arg1 message:(id)arg2 ;
@end

