/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:43 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTLocation, NSArray;

@interface RTVisitLocationPoints : NSObject {

	RTLocation* _centroid;
	NSArray* _locations;

}

@property (nonatomic,readonly) NSArray * locations;                //@synthesize locations=_locations - In the implementation block
@property (nonatomic,readonly) RTLocation * centroid;              //@synthesize centroid=_centroid - In the implementation block
-(id)init;
-(id)description;
-(double)duration;
-(RTLocation *)centroid;
-(NSArray *)locations;
-(id)initWithLocations:(id)arg1 ;
-(id)lastDate;
-(id)firstDate;
-(void)enumerateLowSpeedSegementsUsingBlock:(id)arg1 block:(/*^block*/id)arg2 ;
@end

