/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTStore.h>

@interface RTVisitStore : RTStore
-(void)_fetchVisitsWithOptions:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)_storeVisit:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)_purgeVisitsPredating:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)fetchVisitsWithOptions:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)storeVisit:(id)arg1 handler:(/*^block*/id)arg2 ;
-(void)purgeVisitsPredating:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

