/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTDistanceCalculator, RTLearnedLocationStore, RTLocationStore, RTMotionActivityManager, RTVisitManager;

@interface RTVisitMetrics : NSObject {

	RTDistanceCalculator* _distanceCalculator;
	RTLearnedLocationStore* _learnedLocationStore;
	RTLocationStore* _locationStore;
	RTMotionActivityManager* _motionActivityManager;
	RTVisitManager* _visitManager;

}
-(id)init;
-(id)initWithDistanceCalculator:(id)arg1 learnedLocationStore:(id)arg2 locationStore:(id)arg3 motionActivityManager:(id)arg4 visitManager:(id)arg5 ;
-(id)locationStoreMetricsForInterval:(id)arg1 ;
-(id)motionMetricsForDateInterval:(id)arg1 ;
-(id)realtimeMetricsForConfiguration:(unsigned long long)arg1 dateInterval:(id)arg2 error:(id*)arg3 ;
-(id)batchedMetricsForConfiguration:(unsigned long long)arg1 dateInterval:(id)arg2 error:(id*)arg3 ;
-(id)metricForPipelineConfiguration:(unsigned long long)arg1 previousVisit:(id)arg2 visit:(id)arg3 ;
-(id)metricsForConfiguration:(unsigned long long)arg1 dateInterval:(id)arg2 error:(id*)arg3 ;
-(BOOL)collectMetricsForDateInterval:(id)arg1 error:(id*)arg2 ;
@end

