/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:41 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSMutableDictionary, RTVisit, RTVisitHyperParameter, NSString, NSDate;

@interface RTVisitPipeline : NSObject {

	NSArray* _modules;
	NSMutableDictionary* _moduleStats;
	RTVisit* _lastVisit;
	unsigned long long _iteration;
	RTVisitHyperParameter* _hyperParameter;
	BOOL _bootStrappingDone;
	NSString* _name;
	NSDate* _lastProcessedLocationDate;

}

@property (nonatomic,retain) NSDate * lastProcessedLocationDate;              //@synthesize lastProcessedLocationDate=_lastProcessedLocationDate - In the implementation block
@property (nonatomic,readonly) NSString * name;                               //@synthesize name=_name - In the implementation block
@property (assign,nonatomic) BOOL bootStrappingDone;                          //@synthesize bootStrappingDone=_bootStrappingDone - In the implementation block
-(id)init;
-(void)dealloc;
-(id)description;
-(NSString *)name;
-(id)initWithModules:(id)arg1 name:(id)arg2 lastVisit:(id)arg3 hyperParameter:(id)arg4 ;
-(id)filterLocations:(id)arg1 ;
-(id)processVisitCluster:(id)arg1 ;
-(id)filterVisit:(id)arg1 ;
-(id)processLocations:(id)arg1 ;
-(BOOL)bootStrappingDone;
-(void)setBootStrappingDone:(BOOL)arg1 ;
-(NSDate *)lastProcessedLocationDate;
-(void)setLastProcessedLocationDate:(NSDate *)arg1 ;
@end

