/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:42 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTXPC : NSObject
+(id)checkClientConnection:(id)arg1 forEntitlements:(id)arg2 ;
+(BOOL)xpcConnection:(id)arg1 hasEntitlement:(id)arg2 ;
+(id)signingIdentifierOfConnection:(id)arg1 ;
+(id)allowInternalFrameworkAccessForConnection:(id)arg1 ;
+(BOOL)checkClientCodeSigning:(id)arg1 error:(id*)arg2 ;
+(id)executablePathOfConnection:(id)arg1 ;
@end

