/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:19:32 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary;

@interface FPFootprintSharingData : NSObject {

	NSDictionary* _processToProcessGroups;
	NSDictionary* _processGroupToObjects;

}

@property (nonatomic,retain) NSDictionary * processToProcessGroups;              //@synthesize processToProcessGroups=_processToProcessGroups - In the implementation block
@property (nonatomic,retain) NSDictionary * processGroupToObjects;               //@synthesize processGroupToObjects=_processGroupToObjects - In the implementation block
-(NSDictionary *)processToProcessGroups;
-(NSDictionary *)processGroupToObjects;
-(void)setProcessToProcessGroups:(NSDictionary *)arg1 ;
-(void)setProcessGroupToObjects:(NSDictionary *)arg1 ;
@end

