/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:19:32 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface FPImageEnumerator : NSObject {

	NSArray* _images;
	unsigned long long _index;

}
-(id)initWithImages:(id)arg1 ;
-(id)nextImageForStart:(unsigned long long)arg1 end:(unsigned long long)arg2 ;
@end

