/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:19:32 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FPImage : NSObject {

	unsigned char _segment;
	unsigned long long _start;
	unsigned long long _size;
	NSString* _name;
	NSString* _ownerPath;

}

@property (assign,nonatomic) unsigned char segment;                 //@synthesize segment=_segment - In the implementation block
@property (assign,nonatomic) unsigned long long start;              //@synthesize start=_start - In the implementation block
@property (assign,nonatomic) unsigned long long size;               //@synthesize size=_size - In the implementation block
@property (nonatomic,readonly) unsigned long long end; 
@property (nonatomic,copy) NSString * name;                         //@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString * ownerPath;                    //@synthesize ownerPath=_ownerPath - In the implementation block
-(NSString *)name;
-(void)setName:(NSString *)arg1 ;
-(unsigned long long)size;
-(unsigned long long)start;
-(unsigned long long)end;
-(void)setSize:(unsigned long long)arg1 ;
-(void)setSegment:(unsigned char)arg1 ;
-(unsigned char)segment;
-(void)setStart:(unsigned long long)arg1 ;
-(NSString *)ownerPath;
-(void)setOwnerPath:(NSString *)arg1 ;
@end

