/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:19:32 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libMemoryResourceException.dylib/libMemoryResourceException.dylib-Structs.h>
@interface FPRangeList : NSObject {

	FPRangeListNode* _rangeListHead;

}
-(void)dealloc;
-(SCD_Struct_FP0)sum;
-(void)_addRangeList:(id)arg1 pageSize:(unsigned long long)arg2 ;
-(void)addRange:(NSRange)arg1 pageSize:(unsigned long long)arg2 memoryTotal:(SCD_Struct_FP0*)arg3 ;
-(void)addRegion:(id)arg1 pageSize:(unsigned long long)arg2 ;
@end

