/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:18:12 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnetwork.dylib/libnetwork.dylib-Structs.h>
#import <libobjc.A.dylib/OS_nw_resolver.h>

@protocol OS_nw_parameters, OS_nw_endpoint, OS_nw_context, OS_dispatch_group, OS_dispatch_queue, OS_nw_array;
@class NSObject, NSString;

@interface NWConcrete_nw_resolver : NSObject <OS_nw_resolver> {

	int status;
	os_unfair_lock_s lock;
	NSObject*<OS_nw_parameters> parameters;
	NSObject*<OS_nw_endpoint> endpoint;
	NSObject*<OS_nw_context> context;
	NSObject*<OS_dispatch_group> cancel_group;
	unsigned dns_service_id;
	DNSServiceRef_tRef dns_service;
	DNSServiceRef_tRef dns_service_secondary_pointer;
	unsigned forced_protocol;
	int dns_error;
	unsigned char flags;
	/*^block*/id update_block;
	/*^block*/id cancel_handler;
	NSObject*<OS_dispatch_queue> client_queue;
	void* query_timer;
	void* crazy_eyeballs_timer;
	NSObject*<OS_nw_array> endpoint_array;
	void* internally_retained_object;
	char log_str[84];
	unsigned is_custom_resolver : 1;
	unsigned used_cached_results : 1;
	unsigned local_only : 1;
	unsigned suppress_logging : 1;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithEndpoint:(id)arg1 parameters:(id)arg2 dns_service_id:(unsigned)arg3 localOnly:(BOOL)arg4 ;
-(void)dealloc;
@end

