/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:18:12 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/OS_nw_protocol_stack.h>

@protocol OS_nw_array, OS_nw_protocol_options;
@class NSObject, NSString;

@interface NWConcrete_nw_protocol_stack : NSObject <OS_nw_protocol_stack> {

	NSObject*<OS_nw_array> application_protocols;
	NSObject*<OS_nw_protocol_options> transport_protocol;
	NSObject*<OS_nw_protocol_options> internet_protocol;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
@end

