/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:49 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libAppletTranslationLibrary.dylib/libAppletTranslationLibrary.dylib-Structs.h>
@class NSDictionary;

@interface AppletConfigurationData : NSObject {

	NSDictionary* internal;

}
+(BOOL)setConfiguration:(id)arg1 error:(id*)arg2 ;
+(os_state_data_s*)dumpState;
+(id)getInstance;
+(void)registerStateHandler;
+(id)extraDebugScriptForModule:(id)arg1 ;
+(BOOL)isValidConfigData:(id)arg1 error:(id*)arg2 ;
+(id)GetStaticConfigurationData;
+(id)dataHash;
+(id)scriptForModule:(id)arg1 ;
+(id)plasticCardScriptForModule:(id)arg1 ;
-(id)init;
@end

