/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:20:44 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libAXSpeechManager.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libAXSpeechManager.dylib/libAXSpeechManager.dylib-Structs.h>
@interface AXEmojiUtilities : NSObject
+(NSRange)emojiRangeFromString:(id)arg1 withSearchRange:(NSRange)arg2 ;
+(id)stringByReplacingEmojiCharactersWithEmojiDescriptions:(id)arg1 stringForPauses:(id)arg2 language:(id)arg3 rangeReplacements:(id)arg4 appendEmojiSuffix:(BOOL)arg5 ;
@end

