/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:17:02 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source, OS_dispatch_queue;
@class NSObject;

@interface ATLTimer : NSObject {

	NSObject*<OS_dispatch_source> _src;
	/*^block*/id _block;
	double _delay;
	NSObject*<OS_dispatch_queue> _queue;

}
-(void)dealloc;
-(void)stopTimer;
-(void)onExpire;
-(void)startTimerWithDelay:(double)arg1 leeway:(double)arg2 ;
-(void)startTimerWithDelay:(double)arg1 ;
-(id)initOnQueue:(id)arg1 withTimerBlock:(/*^block*/id)arg2 ;
-(void)addDelay:(double)arg1 ;
@end

