/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:17:02 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libAppletTranslationLibrary.dylib/libAppletTranslationLibrary.dylib-Structs.h>
@interface DERDecoder : NSObject
+(id)dataWithSource:(id)arg1 item:(const SCD_Struct_EM0*)arg2 ;
+(id)DecodeItem:(id)arg1 outTag:(unsigned long long*)arg2 outError:(id*)arg3 ;
+(id)DecodeSequence:(id)arg1 specification:(id)arg2 unordered:(BOOL)arg3 ignoreUnknownTags:(BOOL)arg4 outError:(id*)arg5 ;
@end

