/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:17:02 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libAppletTranslationLibrary.dylib/libAppletTranslationLibrary.dylib-Structs.h>
@interface HashHelper : NSObject {

	CC_SHA256state_st ctx;

}
+(id)hashHelper;
-(id)init;
-(id)addObject:(id)arg1 ;
-(id)getHash;
-(id)addData:(id)arg1 ;
-(id)addDictionary:(id)arg1 ;
-(id)addNumber:(id)arg1 ;
-(id)addString:(id)arg1 ;
-(id)addArray:(id)arg1 ;
-(id)addDateComponents:(id)arg1 ;
-(id)addData:(void*)arg1 withLength:(unsigned long long)arg2 ;
@end

