/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:17:02 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MifareSubDecoder
@required
+(id)getAppletStateAndHistory:(id)arg1 withApplet:(id)arg2 withPackage:(id)arg3 withModule:(id)arg4 withError:(id*)arg5;
+(BOOL)canDecodeSPId:(unsigned char)arg1;
+(id)getServiceProvider:(unsigned char)arg1;
+(id)getEmReentryDelayMs;
+(BOOL)didTransactionError:(const /*function pointer*/void**)arg1 withTransactionResult:(unsigned short*)arg2;

@end

