/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:17:02 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SlalomReadOperation : NSObject {

	unsigned short serviceCode;
	unsigned short blockNumber;

}

@property (assign) unsigned short serviceCode; 
@property (assign) unsigned short blockNumber; 
-(id)description;
-(unsigned short)serviceCode;
-(unsigned short)blockNumber;
-(void)setServiceCode:(unsigned short)arg1 ;
-(void)setBlockNumber:(unsigned short)arg1 ;
@end

