/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:17:02 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/ATLStatefulDecoder.h>

@interface WuluDecoder : NSObject <ATLStatefulDecoder> {

	unsigned long long decoderState;
	BOOL debug;

}
+(id)getInstance;
-(id)init;
-(void)cleanup;
-(id)getState:(id)arg1 ;
-(id)getAppletStateAndHistory:(id)arg1 withError:(id*)arg2 ;
-(id)getHistory:(id)arg1 error:(id*)arg2 ;
-(id)parseFile18:(id)arg1 ;
-(void)parseTransit:(id)arg1 file1E:(id)arg2 into:(id)arg3 ;
-(void)parseTransitApollo:(id)arg1 transactionType:(unsigned char)arg2 file1E:(id)arg3 into:(id)arg4 ;
-(void)parseTransitKepler:(id)arg1 transactionType:(unsigned char)arg2 file1E:(id)arg3 into:(id)arg4 ;
-(id)resolveTypeDetailKepler:(unsigned char)arg1 ;
-(void)parseTransitKeplerBus:(id)arg1 transactionType:(unsigned char)arg2 file1E:(id)arg3 into:(id)arg4 ;
-(void)parseTransitKeplerMetro:(id)arg1 transactionType:(unsigned char)arg2 file1E:(id)arg3 into:(id)arg4 ;
-(id)resolveTypeDetailApollo:(unsigned char)arg1 ;
-(void)parseTransitApolloMetro:(id)arg1 transactionType:(unsigned char)arg2 file1E:(id)arg3 into:(id)arg4 ;
-(void)parseTransitApolloBus:(id)arg1 transactionType:(unsigned char)arg2 file1E:(id)arg3 into:(id)arg4 ;
-(id)parseStartEvent:(id)arg1 withApplet:(id)arg2 withError:(id*)arg3 ;
-(id)parseEndEvent:(id)arg1 withApplet:(id)arg2 withError:(id*)arg3 ;
-(id)parseHCIEvent:(id)arg1 withApplet:(id)arg2 withPackage:(id)arg3 withModule:(id)arg4 withTransceiver:(id)arg5 withError:(id*)arg6 ;
-(id)getAppletStateAndHistory:(id)arg1 withApplet:(id)arg2 withPackage:(id)arg3 withModule:(id)arg4 withError:(id*)arg5 ;
-(id)GetAppletProperties:(id)arg1 withPackage:(id)arg2 withModule:(id)arg3 withTransceiver:(id)arg4 withError:(id*)arg5 ;
-(id)processEndOfTransaction:(id)arg1 withApplet:(id)arg2 withPackage:(id)arg3 withModule:(id)arg4 withError:(id*)arg5 ;
@end

