/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:17:02 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData, NSMutableArray, NSDictionary, NSNumber;

@interface WuluReaderContext : NSObject {

	NSData* _file15;
	NSData* _file17;
	NSMutableArray* _file18_array;
	NSMutableArray* _file1E_array;
	NSDictionary* _file1A_dict;
	NSNumber* _balance;

}

@property (assign,nonatomic) NSData * file15;                            //@synthesize file15=_file15 - In the implementation block
@property (assign,nonatomic) NSData * file17;                            //@synthesize file17=_file17 - In the implementation block
@property (assign,nonatomic) NSMutableArray * file18_array;              //@synthesize file18_array=_file18_array - In the implementation block
@property (assign,nonatomic) NSMutableArray * file1E_array;              //@synthesize file1E_array=_file1E_array - In the implementation block
@property (assign,nonatomic) NSDictionary * file1A_dict;                 //@synthesize file1A_dict=_file1A_dict - In the implementation block
@property (assign,nonatomic) NSNumber * balance;                         //@synthesize balance=_balance - In the implementation block
+(id)readAllFiles:(id)arg1 debug:(BOOL)arg2 error:(id*)arg3 ;
-(NSNumber *)balance;
-(void)setBalance:(NSNumber *)arg1 ;
-(NSData *)file15;
-(NSData *)file17;
-(NSDictionary *)file1A_dict;
-(NSMutableArray *)file18_array;
-(NSMutableArray *)file1E_array;
-(id)readAll:(id)arg1 debug:(BOOL)arg2 error:(id*)arg3 ;
-(id)readBalance:(id)arg1 error:(id*)arg2 ;
-(id)readBinary:(id)arg1 sfi:(unsigned char)arg2 error:(id*)arg3 ;
-(void)setFile15:(NSData *)arg1 ;
-(void)setFile17:(NSData *)arg1 ;
-(void)setFile18_array:(NSMutableArray *)arg1 ;
-(void)setFile1E_array:(NSMutableArray *)arg1 ;
-(id)readRecord:(id)arg1 sfi:(unsigned char)arg2 index:(unsigned char)arg3 error:(id*)arg4 ;
-(void)setFile1A_dict:(NSDictionary *)arg1 ;
-(void)dumpAllFiles;
@end

