/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:54 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACM2SVHTTPHandler.h>

@interface ACM2SVHTTPSendSecurityCodeHandler : ACM2SVHTTPHandler
-(id)initWithContext:(id)arg1 ;
-(id)convertErrorToACMError:(id)arg1 ;
@end

