/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:53 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACCHTTPHandler.h>

@interface ACMHTTPHandler : ACCHTTPHandler
-(id)components;
-(id)iForgotURL;
-(id)environmentPreferences;
-(id)serverHosts;
-(id)serverAttemptsDelays;
@end

