/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:54 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIImage, UIColor, NSString;


@protocol ACMSignInDialogSimpleProtocol <ACMSignInDialogProtocol>
@property (nonatomic,retain) UIImage * logo; 
@property (nonatomic,retain) UIColor * backgroundColor; 
@property (nonatomic,retain) NSString * accountNameFieldPlaceholder; 
@required
-(UIColor *)backgroundColor;
-(void)setBackgroundColor:(id)arg1;
-(UIImage *)logo;
-(void)setLogo:(id)arg1;
-(void)setAccountNameFieldPlaceholder:(id)arg1;
-(NSString *)accountNameFieldPlaceholder;

@end

