/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:56 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftFoundation.dylib/libswiftFoundation.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface _TtCC10FoundationP33_6DA0945A07226B3278459E9368612FF427__KVOKeyPathBridgeMachinery9BridgeKey : NSObject <NSCopying> {

	 value;

}

@property (readonly,nonatomic) long long hash; 
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(long long)hash;
-(id)copyWithZone:(void*)arg1 ;
@end

