/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:56 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtCCE10FoundationCSo7NSTimer14TimerPublisherP33_DD84C790B576E78DF8AF5A5C9BB4E58D19RoutingSubscription : _UKNOWN_SUPERCLASS_ {

	 lock;
	 inner;
	 subscribers;
	 _lockedIsConnected;

}
@end

