/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:56 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtC10FoundationP33_5692656F4C05BA2A580AE9322E9FB0A614__PlistDecoder : _UKNOWN_SUPERCLASS_ {

	 storage;
	 options;
	 codingPath;

}
@end

