/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:56 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Foundation.__NSErrorRecoveryAttempter : _UKNOWN_SUPERCLASS_
-(BOOL)attemptRecoveryFromError:(id)arg1 optionIndex:(long long)arg2 ;
-(void)attemptRecoveryFromError:(id)arg1 optionIndex:(long long)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void*)arg5 ;
@end

