/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:15:27 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFPreferenceObserver : NSObject {

	/*^block*/id _callback;

}

@property (copy) id callback;              //@synthesize callback=_callback - In the implementation block
-(void)dealloc;
-(void)stop;
-(id)callback;
-(void)setCallback:(id)arg1 ;
-(void)start:(/*^block*/id)arg1 ;
-(void)handlePreferencesOrProfileChanged;
@end

