/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:15:26 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSData, NSArray;


@protocol NFTagF
@property (nonatomic,copy,readonly) NSData * IDm; 
@property (nonatomic,copy,readonly) NSData * PMm; 
@property (nonatomic,copy,readonly) NSData * SystemCode; 
@property (nonatomic,copy,readonly) NSArray * allSystemCodes; 
@required
-(NSData *)IDm;
-(NSData *)PMm;
-(NSData *)SystemCode;
-(NSArray *)allSystemCodes;

@end

