/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:15:26 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFWeakReference : NSObject {

	id _store;

}

@property (assign,setter=setObject:,getter=getObject,nonatomic) id object; 
+(id)weakReferenceWithObject:(id)arg1 ;
-(void)dealloc;
-(id)initWithObject:(id)arg1 ;
-(void)setObject:(id)arg1 ;
-(id)getObject;
@end

