/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:55 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libdns_services.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libdns_services.dylib/OS_dnssd_object.h>
#import <libobjc.A.dylib/OS_dnssd_getaddrinfo.h>

@protocol OS_dnssd_getaddrinfo <OS_dnssd_object>
@end


@class NSString;

@interface OS_dnssd_getaddrinfo : OS_dnssd_object <OS_dnssd_getaddrinfo>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@end

