/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:55 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libxpc_datastores.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libxpc_datastores.dylib/OS_xpc_datastore_object.h>
#import <libobjc.A.dylib/XDS_xpc_datastore_publisher.h>

@protocol OS_dispatch_queue;
@class NSObject, NSString;

@interface OS_xpc_datastore_publisher : OS_xpc_datastore_object <XDS_xpc_datastore_publisher> {

	NSObject*<OS_dispatch_queue> pending_work_dq;
	NSObject*<OS_dispatch_queue> dq;
	/*^block*/id publish_data;
	unsigned activated : 1;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)copyCurrentStateWithReqType:(unsigned long long)arg1 ;
@end

