/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:55 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libxpc_datastores.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol XDS_xpc_datastore_publisher <XDS_xpc_datastore_object>
@end

