/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:10:20 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_dispatch_object.h>
#import <libobjc.A.dylib/OS_dispatch_mach.h>

@protocol OS_dispatch_mach <OS_dispatch_object>
@end


@class NSString;

@interface OS_dispatch_mach : OS_dispatch_object <OS_dispatch_mach>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(oneway void)release;
-(void)_xref_dispose;
@end

