/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:10:20 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface OS_object : NSObject
-(id)init;
-(unsigned long long)retainCount;
-(id)retain;
-(oneway void)release;
-(void)_xref_dispose;
-(BOOL)retainWeakReference;
-(BOOL)allowsWeakReference;
@end

