/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:49 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/FPAuxDataType.h>

@interface FPAuxData : NSObject <FPAuxDataType> {

	BOOL _aggregate;
	long long _value;

}

@property (readonly) long long value;                                    //@synthesize value=_value - In the implementation block
@property (getter=shouldAggregate,readonly) BOOL aggregate;              //@synthesize aggregate=_aggregate - In the implementation block
@property (readonly) BOOL isContainer; 
@property (readonly) id jsonRepresentation; 
-(BOOL)isContainer;
-(id)jsonRepresentation;
-(BOOL)shouldAggregate;
-(long long)value;
-(id)initWithValue:(long long)arg1 shouldAggregate:(BOOL)arg2 ;
@end

