/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:49 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libMemoryResourceException.dylib/libMemoryResourceException.dylib-Structs.h>
#import <libobjc.A.dylib/FPOutputFormatter.h>

@class NSString, NSMutableDictionary, NSMutableArray;

@interface FPOutputFormatterJSON : NSObject <FPOutputFormatter> {

	BOOL _isPageSizeSet;
	NSString* _path;
	NSMutableDictionary* _data;
	NSMutableArray* _processes;

}

@property (nonatomic,retain) NSMutableDictionary * data;              //@synthesize data=_data - In the implementation block
@property (nonatomic,retain) NSMutableArray * processes;              //@synthesize processes=_processes - In the implementation block
@property (assign,nonatomic) BOOL isPageSizeSet;                      //@synthesize isPageSizeSet=_isPageSizeSet - In the implementation block
@property (nonatomic,copy) NSString * path;                           //@synthesize path=_path - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setProcesses:(NSMutableArray *)arg1 ;
-(NSMutableArray *)processes;
-(void)setPath:(NSString *)arg1 ;
-(NSString *)path;
-(id)initWithPath:(id)arg1 ;
-(NSMutableDictionary *)data;
-(void)end;
-(void)setData:(NSMutableDictionary *)arg1 ;
-(void)printSummaryCategories:(id)arg1 sortedKeys:(id)arg2 total:(SCD_Struct_FP1*)arg3 hadErrors:(BOOL)arg4 ;
-(void)printProcessHeader:(id)arg1 ;
-(void)printProcessTotal:(id)arg1 forProcess:(id)arg2 ;
-(void)endProcessHeader:(id)arg1 ;
-(void)printProcessCategories:(id)arg1 sortedKeys:(id)arg2 total:(SCD_Struct_FP1*)arg3 ;
-(void)printProcessAuxData:(NSDictionary*)arg1 ;
-(void)printProcessesWithWarnings:(id)arg1 processesWithErrors:(id)arg2 globalErrors:(id)arg3 ;
-(void)printGlobalAuxData:(NSDictionary*)arg1 ;
-(id)JSONForCategories:(id)arg1 ;
-(BOOL)isPageSizeSet;
-(void)setIsPageSizeSet:(BOOL)arg1 ;
@end

