/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:49 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FPOutputFormatter <NSObject>
@optional
-(void)printSharedCategories:(id)arg1 sortedKeys:(id)arg2 sharedWith:(id)arg3 forProcess:(id)arg4 total:(SCD_Struct_FP1*)arg5;
-(void)printVmmapLikeOutputForProcess:(id)arg1 regions:(id)arg2;

@required
-(void)end;
-(void)printSummaryCategories:(id)arg1 sortedKeys:(id)arg2 total:(SCD_Struct_FP1*)arg3 hadErrors:(BOOL)arg4;
-(void)printProcessHeader:(id)arg1;
-(void)printProcessTotal:(id)arg1 forProcess:(id)arg2;
-(void)endProcessHeader:(id)arg1;
-(void)printProcessCategories:(id)arg1 sortedKeys:(id)arg2 total:(SCD_Struct_FP1*)arg3;
-(void)printProcessAuxData:(NSDictionary*)arg1;
-(void)printProcessesWithWarnings:(id)arg1 processesWithErrors:(id)arg2 globalErrors:(id)arg3;
-(void)printGlobalAuxData:(NSDictionary*)arg1;

@end

