/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:12:34 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct __IDXIndex* IDXIndexRef;

typedef struct __CFURL* CFURLRef;

typedef struct _NSZone* NSZoneRef;

typedef struct __CFString* CFStringRef;

typedef struct __CFArray* CFArrayRef;

typedef struct {
	long long field1;
	long long field2;
} SCD_Struct_Me5;

