/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:10:34 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnetwork.dylib/libnetwork.dylib-Structs.h>
#import <libnetwork.dylib/NWConcrete_nw_endpoint.h>

@interface NW_URL_ENDPOINT_CLS : NWConcrete_nw_endpoint {

	CFURLRef url_ref;
	unsigned short port;
	char* url;
	char* scheme;
	char* hostname;
	char* path;
	char* sanitized_url;
	char url_hash[9];

}
-(void)dealloc;
-(unsigned)type;
-(id)copyDictionary;
-(id)initWithURL:(const char*)arg1 ;
-(unsigned short)port;
-(const char*)hostname;
-(char*)createDescription:(BOOL)arg1 ;
-(BOOL)isEqualToEndpoint:(id)arg1 matchInterface:(BOOL)arg2 matchParent:(BOOL)arg3 ;
-(id)copyEndpoint;
-(unsigned long long)getHash;
-(const char*)domainForPolicy;
@end

