/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:49 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libAppleSSEExt.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Timer : NSObject
+(id)timerWithTimeInterval:(double)arg1 block:(/*^block*/id)arg2 ;
-(void)cancel;
-(id)initWithTimeInterval:(double)arg1 block:(/*^block*/id)arg2 ;
@end

