/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:11:23 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libboringssl.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/OS_boringssl_psk.h>

@protocol OS_dispatch_data;
@class NSObject, NSString;

@interface boringssl_concrete_boringssl_psk : NSObject <OS_boringssl_psk> {

	NSObject*<OS_dispatch_data> key;
	NSObject*<OS_dispatch_data> identity;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@end

