/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:50 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtC10FoundationP33_45BFD3D387700B862E3A7353B97EF7ED21__CharacterSetStorage : _UKNOWN_SUPERCLASS_ {

	 _backing;

}
@end

