/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:50 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtC10FoundationP33_5692656F4C05BA2A580AE9322E9FB0A614__PlistDecoder : _UKNOWN_SUPERCLASS_ {

	 storage;
	 options;
	 codingPath;

}
@end

