/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:50 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Foundation.__NSErrorRecoveryAttempter : _UKNOWN_SUPERCLASS_
-(void)attemptRecoveryFromError:(id)arg1 optionIndex:(long long)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void*)arg5 ;
-(BOOL)attemptRecoveryFromError:(id)arg1 optionIndex:(long long)arg2 ;
@end

