/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:20 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libBasebandManager.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct object {
	dispatch_object_s fObj;
} object;

typedef struct queue {
	object fObj;
} queue;

typedef struct block<void ()(CMCallHandedness)> {
	/*^block*/id fBlock;
} block<void ()(CMCallHandedness)>;

