/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:50 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/swift/libswiftNetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Network._NWConnection : _UKNOWN_SUPERCLASS_ {

	 nw;
	 _state;
	 _stateUpdateHandler;
	 _currentPath;
	 _pathUpdateHandler;
	 _viabilityUpdateHandler;
	 _betterPathUpdateHandler;
	 endpoint;
	 parameters;
	 _queue;

}
@end

