/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:10:38 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libMobileGestaltExtensions.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MobileGestaltHelper;
@class NSXPCConnection;

@interface MobileGestaltHelperProxy : NSObject {

	int _error;
	id<MobileGestaltHelper> _helper;
	NSXPCConnection* _connection;

}

@property (assign) int error;                                     //@synthesize error=_error - In the implementation block
@property (readonly) id<MobileGestaltHelper> helper;              //@synthesize helper=_helper - In the implementation block
@property (readonly) NSXPCConnection * connection;                //@synthesize connection=_connection - In the implementation block
+(id)proxy;
-(id)init;
-(void)dealloc;
-(void)invalidate;
-(int)error;
-(void)setError:(int)arg1 ;
-(NSXPCConnection *)connection;
-(id<MobileGestaltHelper>)helper;
-(BOOL)proxyRebuildCache;
@end

