/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:50 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <CoreFoundation/NSSet.h>

@interface __SwiftNativeNSSetBase : NSSet {

	RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> > refCounts;

}
-(void)dealloc;
-(oneway void)release;
-(id)autorelease;
-(id)retain;
-(unsigned long long)retainCount;
-(BOOL)allowsWeakReference;
-(BOOL)_isDeallocating;
-(BOOL)_tryRetain;
-(BOOL)retainWeakReference;
@end

