/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:28:50 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libswiftCore.dylib/Swift.__SwiftNativeNSArray.h>
#import <libobjc.A.dylib/Swift._NSArrayCore.h>

@interface Swift.__SwiftNativeNSArrayWithContiguousStorage : Swift.__SwiftNativeNSArray <Swift._NSArrayCore>

@property (readonly,nonatomic) long long count; 
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3 ;
-(long long)count;
-(id)copyWithZone:(void*)arg1 ;
-(id)objectAtIndex:(long long)arg1 ;
-(void)getObjects:(id*)arg1 range:(SCD_Struct_Sw1)arg2 ;
@end

