/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:18:28 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDWiFiSoftAP : PBCodable <NSCopying> {

	unsigned long long _misToSoftAPActiveTimeInMilliseconds;
	unsigned long long _sessionDuration;
	unsigned long long _timestamp;
	unsigned _appleDeviceConnectCount;
	unsigned _appleDeviceDisconnectCount;
	unsigned _bringUpMethod;
	unsigned _otherDeviceConnectCount;
	unsigned _otherDeviceDisconnectCount;
	unsigned _reasonCode;
	unsigned _teardownReason;
	SCD_Struct_AW14 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                        //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasMisToSoftAPActiveTimeInMilliseconds; 
@property (assign,nonatomic) unsigned long long misToSoftAPActiveTimeInMilliseconds;              //@synthesize misToSoftAPActiveTimeInMilliseconds=_misToSoftAPActiveTimeInMilliseconds - In the implementation block
@property (assign,nonatomic) BOOL hasBringUpMethod; 
@property (assign,nonatomic) unsigned bringUpMethod;                                              //@synthesize bringUpMethod=_bringUpMethod - In the implementation block
@property (assign,nonatomic) BOOL hasReasonCode; 
@property (assign,nonatomic) unsigned reasonCode;                                                 //@synthesize reasonCode=_reasonCode - In the implementation block
@property (assign,nonatomic) BOOL hasTeardownReason; 
@property (assign,nonatomic) unsigned teardownReason;                                             //@synthesize teardownReason=_teardownReason - In the implementation block
@property (assign,nonatomic) BOOL hasSessionDuration; 
@property (assign,nonatomic) unsigned long long sessionDuration;                                  //@synthesize sessionDuration=_sessionDuration - In the implementation block
@property (assign,nonatomic) BOOL hasAppleDeviceConnectCount; 
@property (assign,nonatomic) unsigned appleDeviceConnectCount;                                    //@synthesize appleDeviceConnectCount=_appleDeviceConnectCount - In the implementation block
@property (assign,nonatomic) BOOL hasOtherDeviceConnectCount; 
@property (assign,nonatomic) unsigned otherDeviceConnectCount;                                    //@synthesize otherDeviceConnectCount=_otherDeviceConnectCount - In the implementation block
@property (assign,nonatomic) BOOL hasAppleDeviceDisconnectCount; 
@property (assign,nonatomic) unsigned appleDeviceDisconnectCount;                                 //@synthesize appleDeviceDisconnectCount=_appleDeviceDisconnectCount - In the implementation block
@property (assign,nonatomic) BOOL hasOtherDeviceDisconnectCount; 
@property (assign,nonatomic) unsigned otherDeviceDisconnectCount;                                 //@synthesize otherDeviceDisconnectCount=_otherDeviceDisconnectCount - In the implementation block
-(void)setMisToSoftAPActiveTimeInMilliseconds:(unsigned long long)arg1 ;
-(void)setHasMisToSoftAPActiveTimeInMilliseconds:(BOOL)arg1 ;
-(BOOL)hasMisToSoftAPActiveTimeInMilliseconds;
-(void)setBringUpMethod:(unsigned)arg1 ;
-(void)setHasBringUpMethod:(BOOL)arg1 ;
-(BOOL)hasBringUpMethod;
-(void)setHasReasonCode:(BOOL)arg1 ;
-(BOOL)hasReasonCode;
-(void)setTeardownReason:(unsigned)arg1 ;
-(void)setHasTeardownReason:(BOOL)arg1 ;
-(BOOL)hasTeardownReason;
-(void)setSessionDuration:(unsigned long long)arg1 ;
-(void)setHasSessionDuration:(BOOL)arg1 ;
-(BOOL)hasSessionDuration;
-(void)setAppleDeviceConnectCount:(unsigned)arg1 ;
-(void)setHasAppleDeviceConnectCount:(BOOL)arg1 ;
-(BOOL)hasAppleDeviceConnectCount;
-(void)setOtherDeviceConnectCount:(unsigned)arg1 ;
-(void)setHasOtherDeviceConnectCount:(BOOL)arg1 ;
-(BOOL)hasOtherDeviceConnectCount;
-(void)setAppleDeviceDisconnectCount:(unsigned)arg1 ;
-(void)setHasAppleDeviceDisconnectCount:(BOOL)arg1 ;
-(BOOL)hasAppleDeviceDisconnectCount;
-(void)setOtherDeviceDisconnectCount:(unsigned)arg1 ;
-(void)setHasOtherDeviceDisconnectCount:(BOOL)arg1 ;
-(BOOL)hasOtherDeviceDisconnectCount;
-(unsigned long long)misToSoftAPActiveTimeInMilliseconds;
-(unsigned)bringUpMethod;
-(unsigned)teardownReason;
-(unsigned long long)sessionDuration;
-(unsigned)appleDeviceConnectCount;
-(unsigned)otherDeviceConnectCount;
-(unsigned)appleDeviceDisconnectCount;
-(unsigned)otherDeviceDisconnectCount;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(unsigned)reasonCode;
-(void)setReasonCode:(unsigned)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned long long)timestamp;
-(id)dictionaryRepresentation;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(void)copyTo:(id)arg1 ;
@end

