/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:07 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTAuthorizationManager.h>
#import <libobjc.A.dylib/CLLocationManagerDelegate.h>

@class CLLocationManager, NSString;

@interface RTAuthorizationManager_Embedded : RTAuthorizationManager <CLLocationManagerDelegate> {

	CLLocationManager* _magicalMomentsLocationManager;
	BOOL _magicalMomentsLocationEnabled;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)isLocationServicesEnabled;
-(void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2 ;
-(void)_setup;
-(id)initWithMetricManager:(id)arg1 platform:(id)arg2 userSessionMonitor:(id)arg3 ;
-(void)_fetchMagicalMomentsLocationUsageEnabled:(/*^block*/id)arg1 ;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)_handleMagicalMomentsLocationAuthChange:(int)arg1 ;
@end

