/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:06 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTDataProviderHeroApp.h>

@interface RTDataProviderHeroApp_Embedded : RTDataProviderHeroApp
-(void)populateDataProviderWithHandler:(/*^block*/id)arg1 ;
-(void)_fetchPredictedApplicationsAtLocation:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)_processLocationApplicationPredictions:(id)arg1 ;
@end

