/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:05 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSUUID, NSNumber, NSDate, NSSet;

@interface RTFingerprintMO : NSManagedObject

@property (nonatomic,copy) NSUUID * identifier; 
@property (nonatomic,copy) NSNumber * settledState; 
@property (nonatomic,copy) NSDate * start; 
@property (nonatomic,retain) NSSet * wifiAccessPoints; 
+(id)fetchRequest;
+(id)managedObjectWithFingerprint:(id)arg1 inManagedObjectContext:(id)arg2 ;
+(id)fetchLastByStartDateInManagedObjectContext:(id)arg1 error:(id*)arg2 ;
@end

