/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:05 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, RTMapItem;

@interface RTHistoryEntryPlaceDisplay : NSObject {

	NSDate* _usageDate;
	RTMapItem* _mapItem;

}

@property (nonatomic,readonly) NSDate * usageDate;               //@synthesize usageDate=_usageDate - In the implementation block
@property (nonatomic,readonly) RTMapItem * mapItem;              //@synthesize mapItem=_mapItem - In the implementation block
-(RTMapItem *)mapItem;
-(NSDate *)usageDate;
-(id)initWithUsageDate:(id)arg1 mapItem:(id)arg2 ;
-(id)init;
-(id)description;
@end

