/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:06 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTLocationStoreMetrics : NSObject {

	unsigned long long _count;
	double _maxIntervalBetweenLocations;

}

@property (assign,nonatomic) unsigned long long count;                        //@synthesize count=_count - In the implementation block
@property (assign,nonatomic) double maxIntervalBetweenLocations;              //@synthesize maxIntervalBetweenLocations=_maxIntervalBetweenLocations - In the implementation block
-(void)setMaxIntervalBetweenLocations:(double)arg1 ;
-(double)maxIntervalBetweenLocations;
-(unsigned long long)count;
-(void)setCount:(unsigned long long)arg1 ;
@end

