/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:07 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSSet;

@interface RTMediaRemoteNotificationPrimingBundleIdentifiersChanged : RTNotification {

	NSSet* _bundleIdentifiers;

}

@property (nonatomic,copy,readonly) NSSet * bundleIdentifiers;              //@synthesize bundleIdentifiers=_bundleIdentifiers - In the implementation block
-(id)initWithBundleIdentifiers:(id)arg1 ;
-(NSSet *)bundleIdentifiers;
@end

