/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:07 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSString;

@interface RTMediaRemoteNotificationNowPlayingInfoChanged : RTNotification {

	NSString* _bundleIdentifier;
	double _duration;
	long long _playbackState;

}

@property (nonatomic,copy,readonly) NSString * bundleIdentifier;              //@synthesize bundleIdentifier=_bundleIdentifier - In the implementation block
@property (nonatomic,readonly) double duration;                               //@synthesize duration=_duration - In the implementation block
@property (nonatomic,readonly) long long playbackState;                       //@synthesize playbackState=_playbackState - In the implementation block
-(long long)playbackState;
-(id)initWithBundleIdentifier:(id)arg1 duration:(double)arg2 playbackState:(long long)arg3 ;
-(NSString *)bundleIdentifier;
-(double)duration;
@end

