/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:07 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPredictionExpertFeatureAddonMO.h>

@interface RTPredictionExpertFeatureAddonTimeOfDayMO : RTPredictionExpertFeatureAddonMO

@property (nonatomic,retain) id endDateComponents; 
@property (nonatomic,retain) id startDateComponents; 
+(id)managedObjectWithStartDateComponents:(id)arg1 endDateComponents:(id)arg2 inManagedObjectContext:(id)arg3 ;
+(id)_managedObjectWithStartDateComponents:(id)arg1 endDateComponents:(id)arg2 inManagedObjectContext:(id)arg3 ;
+(id)managedObjectWithDateRange:(id)arg1 inManagedObjectContext:(id)arg2 ;
@end

