/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:05 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
@interface RTPriorityQueue : NSObject {

	CFBinaryHeapRef _heap;

}

@property (nonatomic,readonly) unsigned long long count; 
-(id)peek;
-(id)dequeue;
-(void)enqueue:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(unsigned long long)count;
-(id)initWithObjects:(id)arg1 ;
@end

