/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:05 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSSet, RTPredictionItemMO, RTPredictionTableMO;

@interface RTPredictionTableEntryMO : NSManagedObject

@property (nonatomic,retain) NSSet * conditions; 
@property (nonatomic,retain) RTPredictionItemMO * item; 
@property (nonatomic,retain) RTPredictionTableMO * predictionTable; 
+(id)managedObjectWithItem:(id)arg1 conditions:(id)arg2 inManagedObjectContext:(id)arg3 ;
@end

