/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:06 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTReachabilityMonitorNotificationReachabilityChanged : RTNotification {

	long long _reachability;

}

@property (nonatomic,readonly) long long reachability;              //@synthesize reachability=_reachability - In the implementation block
-(long long)reachability;
-(id)initWithReachability:(long long)arg1 ;
@end

