/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:07 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTRouteLocationPreprocessor : NSObject
+(id)preprocessLocations:(id)arg1 error:(id*)arg2 ;
+(long long)findProperEndFromLocations:(id)arg1 ;
+(id)selectBestSubSequenceFromLocations:(id)arg1 error:(id*)arg2 ;
+(unsigned long long)idealPreviousLocationIndex:(id)arg1 from:(unsigned long long)arg2 ;
+(double)costOfLocation:(id)arg1 ;
@end

