/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:04 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSUUID, NSDate, NSString, NSOrderedSet;

@interface RTRouteMO : NSManagedObject

@property (nonatomic,retain) NSUUID * identifier; 
@property (nonatomic,copy) NSDate * start; 
@property (nonatomic,copy) NSDate * stop; 
@property (nonatomic,retain) NSUUID * originLocationOfInterestIdentifier; 
@property (nonatomic,retain) NSUUID * destinationLocationOfInterestIdentifier; 
@property (nonatomic,retain) NSUUID * originVisitIdentifier; 
@property (nonatomic,retain) NSUUID * destinationVisitIdentifier; 
@property (nonatomic,copy) NSString * name; 
@property (nonatomic,retain) NSOrderedSet * locations; 
+(id)fetchRequest;
+(id)managedObjectWithRoute:(id)arg1 inManagedObjectContext:(id)arg2 ;
@end

