/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:05 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface RTRuntime : NSObject
+(id)classesFromImages:(id)arg1 ;
+(id)subclassesOfClass:(Class)arg1 images:(id)arg2 includeParentClass:(BOOL)arg3 ;
+(id)routineImageNames;
+(id)directSubclassesOfClass:(Class)arg1 images:(id)arg2 includeParentClass:(BOOL)arg3 ;
+(id)routineClassStrings;
+(id)routineSubclassesOfClass:(Class)arg1 ;
+(id)routineClasses;
@end

