/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:06 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSUUID;

@interface RTStateWeeklyStatisticsEl : NSObject {

	double _numOfClustEntPerWeek;
	double _avgAggTime_s;
	double _stdAggTime_s;
	double _daysPerWeek;
	NSUUID* _stateUUID;
	double _topMedian;

}

@property (assign,nonatomic) double numOfClustEntPerWeek;              //@synthesize numOfClustEntPerWeek=_numOfClustEntPerWeek - In the implementation block
@property (assign,nonatomic) double avgAggTime_s;                      //@synthesize avgAggTime_s=_avgAggTime_s - In the implementation block
@property (assign,nonatomic) double stdAggTime_s;                      //@synthesize stdAggTime_s=_stdAggTime_s - In the implementation block
@property (assign,nonatomic) double daysPerWeek;                       //@synthesize daysPerWeek=_daysPerWeek - In the implementation block
@property (nonatomic,copy) NSUUID * stateUUID;                         //@synthesize stateUUID=_stateUUID - In the implementation block
@property (assign,nonatomic) double topMedian;                         //@synthesize topMedian=_topMedian - In the implementation block
-(NSUUID *)stateUUID;
-(void)setStateUUID:(NSUUID *)arg1 ;
-(void)setAvgAggTime_s:(double)arg1 ;
-(void)setStdAggTime_s:(double)arg1 ;
-(void)setDaysPerWeek:(double)arg1 ;
-(void)setNumOfClustEntPerWeek:(double)arg1 ;
-(void)setTopMedian:(double)arg1 ;
-(double)numOfClustEntPerWeek;
-(double)avgAggTime_s;
-(double)stdAggTime_s;
-(double)daysPerWeek;
-(double)topMedian;
-(id)init;
@end

