/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:07 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTLocationOfInterest, AWDCoreRoutineTrafficConditions;

@interface RTTrafficConditionsMetric : NSObject {

	RTLocationOfInterest* _locationOfInterest;
	AWDCoreRoutineTrafficConditions* _metric;

}

@property (nonatomic,readonly) RTLocationOfInterest * locationOfInterest;              //@synthesize locationOfInterest=_locationOfInterest - In the implementation block
@property (nonatomic,readonly) AWDCoreRoutineTrafficConditions * metric;               //@synthesize metric=_metric - In the implementation block
-(RTLocationOfInterest *)locationOfInterest;
-(AWDCoreRoutineTrafficConditions *)metric;
-(id)initWithPLOIETA:(id)arg1 ;
-(void)updatePrecisionRecallWithVisitedLocation:(id)arg1 ;
-(id)init;
-(id)description;
@end

