/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:05 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSArray;

@interface RTVehicleEventNotification : RTNotification {

	NSArray* _vehicleEvents;

}

@property (nonatomic,readonly) NSArray * vehicleEvents;              //@synthesize vehicleEvents=_vehicleEvents - In the implementation block
-(NSArray *)vehicleEvents;
-(id)initWithVehicleEvents:(id)arg1 ;
@end

