/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:06 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTVisitMonitorDelegate <NSObject>
@optional
-(void)onVisitIncident:(id)arg1 error:(id)arg2;
-(void)onLeechedVisitIncident:(id)arg1 error:(id)arg2;
-(void)onVisitMonitorStateChanged:(id)arg1;
-(void)onLowConfidenceVisitIncident:(id)arg1 error:(id)arg2;

@end

