/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:18:03 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libobjc.A.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Object : _UKNOWN_SUPERCLASS_ {

	Class isa;

}
+(id)class;
+(void)release;
+(id)initialize;
+(id)autorelease;
+(id)retain;
-(void)release;
-(id)autorelease;
-(id)retain;
@end

