/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:53 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libBKDM1.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSNumber;

@interface ADEvent : NSObject {

	long long _operation;
	long long _storage;
	long long _key;
	NSString* _stringKey;
	NSNumber* _value;

}

@property (assign) long long operation;               //@synthesize operation=_operation - In the implementation block
@property (assign) long long storage;                 //@synthesize storage=_storage - In the implementation block
@property (assign) long long key;                     //@synthesize key=_key - In the implementation block
@property (retain) NSString * stringKey;              //@synthesize stringKey=_stringKey - In the implementation block
@property (retain) NSNumber * value;                  //@synthesize value=_value - In the implementation block
+(id)eventWithOperation:(long long)arg1 Storage:(long long)arg2 Key:(long long)arg3 Value:(id)arg4 ;
+(id)eventWithOperation:(long long)arg1 Storage:(long long)arg2 StringKey:(id)arg3 Value:(id)arg4 ;
-(id)description;
-(long long)key;
-(long long)storage;
-(NSNumber *)value;
-(long long)operation;
-(void)setOperation:(long long)arg1 ;
-(void)setValue:(NSNumber *)arg1 ;
-(void)setKey:(long long)arg1 ;
-(void)setStorage:(long long)arg1 ;
-(void)setStringKey:(NSString *)arg1 ;
-(id)initWithOperation:(long long)arg1 Storage:(long long)arg2 Key:(long long)arg3 StringKey:(id)arg4 Value:(id)arg5 ;
-(NSString *)stringKey;
-(id)stringKey:(long long)arg1 useCase:(int)arg2 prearmedApplePay:(BOOL)arg3 ;
-(void)pushToAggregateDictionary:(long long)arg1 useCase:(int)arg2 prearmedApplePay:(BOOL)arg3 ;
@end

