/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:53 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libBKDM1.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface ADStorage : NSObject {

	NSMutableArray* _eventList;

}
+(id)storage;
-(id)init;
-(void)clear;
-(void)addEvent:(id)arg1 ;
-(void)pushToAggregateDictionary:(long long)arg1 useCase:(int)arg2 prearmedApplePay:(BOOL)arg3 ;
@end

