/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:53 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libBKDM1.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libBKDM1.dylib/libBKDM1.dylib-Structs.h>
@class NSMutableDictionary, NSString, NSDate, ADStorage, BiometricKitXPCServerMesa;

@interface BiometricKitDStatistics : NSObject {

	NSMutableDictionary* _templateStats;
	BOOL _fingerOn;
	BOOL _unlockOperationInProgress;
	BOOL _unlockOperationStartedByCommand;
	BOOL _matchOperationInProgress;
	BOOL _haveMatchResult;
	BOOL _waitingForMatchResult;
	BOOL _haveImageToProcess;
	BOOL _matchWithDesensePauseLogged;
	BOOL _deviceWokeUpByHomeButton;
	BOOL _deviceWokeUpByLiftToWake;
	BOOL _pressureMitigationUsed;
	BOOL _prearmedApplePay;
	BOOL _lastMatchResultWakePin;
	BOOL _homeButtonPressedDuringTouch;
	int _lastBioOp;
	long long _lastStartedMatch;
	int _lastMatchUseCase;
	NSString* _clientName;
	unsigned long long _lastMatchResultID;
	unsigned _sksLockState;
	unsigned _previousSKSLockState;
	unsigned long long _sensorOperationMode;
	NSDate* _sensorOperationStartDate;
	unsigned long long _imagesPerFingerDown;
	unsigned long long _sensorCaptureRestartsPerFingerDown;
	unsigned long long _imageCaptureRestartsPerFingerDown;
	unsigned long long _failTouchesToUnlock;
	unsigned long long _failQuickTapsToUnlock;
	unsigned long long _failTouchesToMatch;
	unsigned long long _matchRestarts;
	long long _calibrationDataState;
	float _modulationRatio;
	ADStorage* _storage;
	BiometricKitXPCServerMesa* _server;

}

@property (assign) BiometricKitXPCServerMesa * server;              //@synthesize server=_server - In the implementation block
+(id)statistics;
+(unsigned)clusterCount:(const SCD_Struct_Bi9*)arg1 ;
-(id)init;
-(void)cancel;
-(void)setServer:(BiometricKitXPCServerMesa *)arg1 ;
-(BiometricKitXPCServerMesa *)server;
-(void)removeIdentity:(id)arg1 ;
-(void)timestampEvent:(unsigned long long)arg1 absoluteTime:(unsigned long long)arg2 ;
-(void)statusMessage:(unsigned)arg1 ;
-(void)startMatchOperation:(id)arg1 ;
-(void)startBioOperation:(id)arg1 ;
-(void)logSensorSelfTestInfo;
-(void)displayStatusChanged:(BOOL)arg1 ;
-(void)matchResult:(id)arg1 withDictionary:(id)arg2 ;
-(void)resetMatchCounts;
-(void)statisticsMessage:(SCD_Struct_Bi6*)arg1 ;
-(void)templateUpdate:(id)arg1 withDictionary:(id)arg2 ;
-(void)addIdentitity:(id)arg1 ;
-(void)homeButtonStateChanged:(BOOL)arg1 ;
-(void)lockStateUpdated:(unsigned)arg1 ;
-(void)removeAllIdentities;
-(void)catacombCorrupted:(long long)arg1 ;
-(void)wakeGestureUpdate:(long long)arg1 ;
-(void)serviceMatch;
-(unsigned long long)totalNodeCount;
-(double)totalArea;
-(void)unlockAttemptStarted:(BOOL)arg1 ;
-(void)matchOperationStarted;
-(void)postEvent:(id)arg1 ;
-(void)matchAttemptFinished:(BOOL)arg1 ;
-(void)matchOperationFinished:(BOOL)arg1 ;
-(BOOL)wasDeviceHibernated:(SCD_Struct_Bi12*)arg1 ;
-(void)updateDailyValues;
-(void)lastImageIsProcessed;
-(BOOL)isPasscodeNeeded;
-(void)logFingerOff;
-(void)handleSensorOperationStatusMessage:(unsigned)arg1 ;
-(BOOL)isMesaEnabled;
-(unsigned long long)totalClusterCount;
-(unsigned long long)totalPrimaryClusterNodeCount;
-(double)totalPrimaryClusterArea;
-(void)logTemplateAttributes:(BOOL)arg1 ;
-(void)logTemplateCountPerUser:(BOOL)arg1 ;
-(void)unlockedByPasscode;
-(void)unlockedByMesa;
-(void)logTemplateMatchCounts;
-(void)unlockAttemptFinished;
-(BOOL)wasPasscodeNeeded;
-(void)unlockAttemptCanceled;
-(BOOL)passcodeNedded:(long long)arg1 ;
-(id)getSensorSelfTestResult;
@end

