/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:23:46 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NFAWDEventProtocol.h>

@class AWDNFCCRSAuthInitExceptionEvent, NSString;

@interface NFAWDCRSAuthInitException : NSObject <NFAWDEventProtocol> {

	AWDNFCCRSAuthInitExceptionEvent* _metric;

}

@property (nonatomic,retain) AWDNFCCRSAuthInitExceptionEvent * metric;              //@synthesize metric=_metric - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(unsigned)getMetricId;
-(id)getMetric;
-(void)updateExceptionUUID:(id)arg1 ;
-(void)setMetric:(AWDNFCCRSAuthInitExceptionEvent *)arg1 ;
-(AWDNFCCRSAuthInitExceptionEvent *)metric;
-(id)init;
-(void)dealloc;
@end

