/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:23:46 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NFNdefMessage.h>

@class NSArray, NSMutableArray, NSString;

@interface NFNdefMessageInternal : NSObject <NSSecureCoding, NFNdefMessage> {

	NSMutableArray* _records;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSArray * records; 
+(id)decodeFromNDEFMessage:(id)arg1 ;
+(id)dataFromNDEFMessage:(id)arg1 ;
+(BOOL)supportsSecureCoding;
-(id)asData;
-(id)decode;
-(id)initWithNDEFMessage:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)description;
-(id)initWithBytes:(const void*)arg1 length:(unsigned)arg2 ;
-(NSArray *)records;
-(void)addRecord:(id)arg1 ;
@end

