/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:23:47 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFPreferenceObserver : NSObject {

	/*^block*/id _callback;

}

@property (copy) id callback;              //@synthesize callback=_callback - In the implementation block
-(void)setCallback:(id)arg1 ;
-(id)callback;
-(void)handlePreferencesChanged;
-(void)updateDiagnosticLogging;
-(void)handleProfilesChanged;
-(void)dealloc;
-(void)stop;
-(void)start;
@end

