/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:23:46 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFWeakReference : NSObject {

	id _store;

}

@property (assign,setter=setObject:,getter=getObject,nonatomic) id object; 
+(id)weakReferenceWithObject:(id)arg1 ;
-(id)getObject;
-(void)dealloc;
-(void)setObject:(id)arg1 ;
-(id)initWithObject:(id)arg1 ;
@end

