/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:13:19 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface __SwiftValue : NSObject <NSCopying>
+(id)allocWithZone:(NSZone*)arg1 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)debugDescription;
-(id)copyWithZone:(NSZone*)arg1 ;
-(const TargetMetadata<swift::InProcess>*)_swiftTypeMetadata;
-(id)_swiftTypeName;
-(const OpaqueValueRef)_swiftValue;
@end

