/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:13:19 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <Foundation/NSIndexSet.h>

@interface __SwiftNativeNSIndexSetBase : NSIndexSet {

	RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> > refCounts;

}
+(BOOL)automaticallyNotifiesObserversForKey:(id)arg1 ;
-(unsigned long long)retainCount;
-(void)dealloc;
-(id)retain;
-(oneway void)release;
-(id)autorelease;
-(BOOL)retainWeakReference;
-(BOOL)allowsWeakReference;
-(BOOL)_tryRetain;
-(BOOL)_isDeallocating;
-(id)initWithCoder:(id)arg1 ;
@end

