/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:13:19 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct {
	unsigned long long field1;
	id field2;
	unsigned long long field3;
	unsigned long long field4[5];
} SCD_Struct_Sw0;

typedef struct {
	long long field1;
	long long field2;
} SCD_Struct_Sw1;

typedef struct _NSZone* NSZoneRef;

typedef struct atomic<swift::RefCountBitsT<swift::RefCountIsInline> > {
	ARefCountBitsT<swift::RefCountIsInline> __a_;
} atomic<swift::RefCountBitsT<swift::RefCountIsInline> >;

typedef struct RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> > {
	atomic<swift::RefCountBitsT<swift::RefCountIsInline> > refCounts;
} RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> >;

typedef const struct OpaqueValue* OpaqueValueRef;

