/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:13:19 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/Swift.__SwiftNativeNSDictionary.h>

@interface Swift.__RawDictionaryStorage : Swift.__SwiftNativeNSDictionary {

	 _count;
	 _capacity;
	 _scale;
	 _reservedScale;
	 _extra;
	 _age;
	 _seed;
	 _rawKeys;
	 _rawValues;

}
-(id)initWithCoder:(id)arg1 ;
@end

