/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:13:19 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol Swift._NSArrayCore <Swift._NSCopying,Swift._NSFastEnumeration>
@property (readonly,nonatomic) long long count; 
@required
-(long long)count;
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3;
-(id)objectAtIndex:(long long)arg1;
-(void)getObjects:(id*)arg1 range:(SCD_Struct_Sw1)arg2;

@end

