/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:13:19 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/Swift.__SwiftNativeNSArrayWithContiguousStorage.h>

@interface Swift.__SwiftDeferredNSArray : Swift.__SwiftNativeNSArrayWithContiguousStorage {

	 _heapBufferBridged_DoNotUse;
	 _nativeStorage;

}

@property (readonly,nonatomic) long long count; 
-(long long)count;
@end

