/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:18:14 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAXSpeechManager.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libAXSpeechManager.dylib/libAXSpeechManager.dylib-Structs.h>
@interface AXEmojiUtilities : NSObject
+(id)stringByReplacingEmojiCharactersWithEmojiDescriptions:(id)arg1 stringForPauses:(id)arg2 language:(id)arg3 rangeReplacements:(id)arg4 appendEmojiSuffix:(BOOL)arg5 ;
+(void)_initializeEmojiStructures:(id)arg1 ;
+(NSRange)emojiRangeFromString:(id)arg1 withSearchRange:(NSRange)arg2 ;
+(id)stringByRemovingEmojiCharacters:(id)arg1 ;
@end

