/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 7, 2019 at 3:21:52 AM Pacific Standard Time
* Operating System: Version 13.2.3 (Build 17B111)
* Image Source: /usr/lib/libAppPatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MIBOMWrapper : NSObject
+(BOOL)extractZipArchiveAtURL:(id)arg1 toURL:(id)arg2 withError:(id*)arg3 ;
@end

