/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:01 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libBKDM1.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface BKCatacomb : NSObject {

	NSString* _catacombDir;

}
+(id)catacombWithDir:(id)arg1 withSerial:(id)arg2 ;
-(int)deleteFile:(id)arg1 ;
-(int)deleteAll;
-(int)recover;
-(int)writeData:(id)arg1 toFile:(id)arg2 ;
-(id)catacombCommitDir;
-(id)catacombPrepareDir;
-(int)syncDir:(id)arg1 ;
-(int)commitWrite;
-(int)readData:(id*)arg1 fromFile:(id)arg2 ;
-(id)init;
-(id)content;
@end

