/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, February 3, 2021 at 10:27:01 PM Australian Eastern Daylight Time
* Operating System: Version 12.4 (Build 16G77)
* Image Source: /usr/lib/libBKDM1.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSLock;

@interface BLTemplateList : NSObject {

	NSMutableDictionary* _identityList;
	NSMutableDictionary* _templateList;
	NSLock* _listLock;

}
-(void)removeIdentity:(id)arg1 ;
-(void)setIdentities:(id)arg1 ;
-(id)allIdentities;
-(id)initWithIdentities:(id)arg1 ;
-(id)identitiesForUser:(unsigned)arg1 ;
-(unsigned long long)countForUser:(unsigned)arg1 ;
-(id)templateNameForIdentity:(id)arg1 ;
-(void)setIdentity:(id)arg1 withTemplateName:(id)arg2 ;
-(void)setIdentitiesForUser:(unsigned)arg1 withTemplateListName:(id)arg2 ;
-(id)identityByUUID:(id)arg1 ;
-(void)dealloc;
-(void)setIdentity:(id)arg1 ;
-(void)removeAll;
@end

